HTML=
SUBDIRS=
LITERATE_HASKELL = Introduction.lhs \
                   Warming-up.lhs \
                   More-on-pattern-matching.lhs \
                   Sieve-of-Eratosthenes.lhs \
                   Fibonacci-series.lhs \
                   Folding-lists.lhs \
                   Data-types.lhs\
                   An-expression-evaluator.lhs\
                   Lambda-calculus.lhs\
                   Modules.lhs\
                   Towards-type-inference.lhs\
                   Unification-algorithm.lhs\

include ${DEFAULT_RULES}

all: default-all
clean: default-clean